import React, { useState } from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { useLanguage } from '../contexts/LanguageContext';
import { Link } from 'react-router-dom';
import { CalculadoraPlegado, CalculadoraMateriales } from '../components/Calculadoras';
import CalculadoraInercia from '../components/CalculadoraInercia';
import CalculadoraCaldereria from '../components/CalculadoraCaldereria';
import { CotizacionTools } from '../components/CotizacionTools';
import { CalculadoraROI, OrdenFabricacionPDF } from '../components/AdministracionTools';
import VideoAIHub from '../components/VideoAIHub';
import ProduccionTools from '../components/ProduccionTools';

const locales = {
  es: {
    heroTitle: "Engineering & Business Hub",
    heroSub: "Herramientas exclusivas y recursos de gestión para dueños de talleres.",
    cat1: "📊 Dirección (Management)",
    cat2: "📐 Ingeniería (Engineering)",
    cat3: "🏭 Producción (Production)",
    cat4: "📺 Videoteca (Fabricontrol TV)",
    bannerTitle: "¿Quieres automatizar esto?",
    bannerSub: "Prueba Fabricontrol Full por 30 días gratis y deja que el sistema calcule todo por ti.",
    bannerBtn: "Prueba Gratis",
    useTool: "Usar Herramienta",
    download: "Descargar Documento",
    
    // Cutting
    c1i1_t: "Optimizador de Nesting DeepNest",
    c1i1_d: "Ahorra hasta un 30% de material. Sube tus DXF y optimiza el corte para Plasma y Láser.",
    
    // Quoting
    c4i1_t: "Calculadora de Costo por Minuto",
    c4i1_d: "Mide el costo real de taller incluyendo insumos, mano de obra y margen.",
    c4i2_t: "Estimador de Tiempo de Producción",
    c4i2_d: "Calcula horas hombre y brinda fechas de entrega certeras a clientes.",
    
    // Management
    c5i1_t: "Calculadora de ROI (Retorno de Inversión)",
    c5i1_d: "Descubre cuánto ahorras automatizando vs el trabajo en Excel.",
    c5i2_t: "Plantilla de Orden de Trabajo",
    c5i2_d: "Formato en PDF ideal para estandarizar la producción en el piso.",
    
    // Podcast
    podTitle: "🎧 Podcast & Guía de Voz IA",
    podSub: "Escucha el análisis profundo de Fabricontrol generado por IA.",
    podFile1: "Podcast: El Futuro del Taller"
  },
  en: {
    heroTitle: "Engineering & Business Hub",
    heroSub: "Exclusive tools and management resources for workshop owners.",
    cat1: "📊 Management (Dirección)",
    cat2: "📐 Engineering (Ingeniería)",
    cat3: "🏭 Production (Producción)",
    cat4: "📺 Video Hub (Videoteca)",
    bannerTitle: "Want to automate this?",
    bannerSub: "Try Fabricontrol Full for 30 days free and let the system calculate everything for you.",
    bannerBtn: "Try for Free",
    useTool: "Use Tool",
    download: "Download Document",
    
    c1i1_t: "DeepNest Nesting Optimizer",
    c1i1_d: "Save up to 30% on materials. Upload DXFs and optimize cuts for Plasma and Laser.",
    
    c4i1_t: "Cost Per Minute Calculator",
    c4i1_d: "Measure true shop cost including supplies, labor, and margin.",
    c4i2_t: "Production Time Estimator",
    c4i2_d: "Calculate man-hours and give accurate delivery dates.",
    
    c5i1_t: "ROI Calculator",
    c5i1_d: "Discover how much you save by automating vs working in Excel.",
    c5i2_t: "Work Order Template",
    c5i2_d: "Ideal PDF format to standardize floor production.",
    
    // Podcast
    podTitle: "🎧 AI Podcast & Voice Guide",
    podSub: "Listen to the deep analysis of FabriControl generated by AI.",
    podFile1: "Podcast: The Future of the Workshop"
  },
  he: {
    heroTitle: "Engineering & Business Hub",
    heroSub: "כלים ומשאבי ניהול בלעדיים לבעלי מפעלים.",
    cat1: "📊 ניהול (Management)",
    cat2: "📐 הנדסה (Engineering)",
    cat3: "🏭 ייצור (Production)",
    cat4: "📺 ספריית וידאו (IA Videos)",
    bannerTitle: "רוצה לעשות אוטומציה לזה?",
    bannerSub: "נסה את Fabricontrol בחינם ל-30 יום ותן למערכת לחשב הכל עבורך.",
    bannerBtn: "נסה בחינם",
    useTool: "השתמש בכלי",
    download: "הורד מסמך",
    
    c1i1_t: "אופטימיזציית Nesting עם DeepNest",
    c1i1_d: "חסוך עד 30% בחומר. העלה את קבצי ה-DXF וייעל את החיתוך עבור פלזמה ולייזר.",
    
    c4i1_t: "מחשבון עלות לדקה",
    c4i1_d: "מדוד עלות אמיתית של המפעל, כולל אספקה, עבודה ושולי רווח.",
    c4i2_t: "מחשבון זמן ייצור",
    c4i2_d: "חשב שעות עבודה וספק תאריכי אספקה מדויקים ללקוחות.",
    
    c5i1_t: "מחשבון החזר השקעה (ROI)",
    c5i1_d: "גלה כמה אתה חוסך באוטומציה לעומת עבודה באקסל.",
    c5i2_t: "תבנית הזמנת עבודה (Work Order)",
    c5i2_d: "פורמט PDF אידיאלי לתקינה בייצור וברצפת העבודה.",
    
    // Podcast
    podTitle: "🎧 פודקאסט ומדריך קולי IA",
    podSub: "האזן לניתוח המעמיק של Fabricontrol שנוצר על ידי בינה מלאכותית.",
    podFile1: "פודקאסט: עתיד המפעל"
  },
};

const RecursosTabs = () => {
  const [activeTab, setActiveTab] = useState(0);
  const { language, isRtl } = useLanguage();
  const l = locales[language] || locales.es;

  const categories = [
    { id: 0, title: l.cat1 },
    { id: 1, title: l.cat2 },
    { id: 2, title: l.cat3 },
    { id: 3, title: l.cat4 }
  ];

  const renderTabContent = () => {
    switch(activeTab) {
      case 0: // Management
        return (
          <div className="space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="grid grid-cols-1 gap-12">
               <CalculadoraROI />
               <CotizacionTools labels={l} />
            </div>
            <div className="flex justify-center">
               <OrdenFabricacionPDF />
            </div>
          </div>
        );
      case 1: // Engineering
        return (
          <div className="space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <CalculadoraCaldereria />
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <CalculadoraInercia />
                <CalculadoraPlegado />
            </div>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <CalculadoraMateriales />
                <div className="bg-white/5 backdrop-blur-xl rounded-[2.5rem] p-8 border border-white/10 hover:-translate-y-2 hover:bg-white/10 hover:shadow-[0_10px_40px_rgba(6,182,212,0.2)] transition-all duration-500 relative overflow-hidden group">
                    <div className="absolute top-0 right-0 w-64 h-64 bg-cyan-400/10 rounded-full blur-[80px] -mr-32 -mt-32 group-hover:bg-cyan-400/20 transition-all duration-700"></div>
                    <div className="relative z-10">
                        <h3 className="text-3xl font-black text-white mb-4 flex items-center gap-4">
                            <span className="bg-white/10 w-12 h-12 rounded-2xl flex items-center justify-center text-2xl group-hover:scale-110 transition-transform">✂️</span> 
                            {l.c1i1_t}
                        </h3>
                        <p className="text-gray-400 text-lg font-medium mb-8 leading-relaxed">
                            {l.c1i1_d}
                        </p>
                        <a href="https://deepnest.io/" target="_blank" rel="noopener noreferrer" className="inline-flex py-4 px-10 bg-gradient-to-r from-slate-700 to-slate-800 hover:from-cyan-600 hover:to-blue-700 border border-white/10 text-white rounded-2xl font-black transition-all duration-300 shadow-xl group-hover:shadow-cyan-500/20 active:scale-95">
                            🖥️ Ir a DeepNest.io
                        </a>
                    </div>
                </div>
            </div>
          </div>
        );
      case 2: // Production
        return <div className="animate-in fade-in slide-in-from-bottom-4 duration-500"><ProduccionTools /></div>;
      case 3: // Videoteca
        return (
          <div className="space-y-16 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <VideoAIHub />
            
            {/* AUDIOTECA / PODCAST SECTION */}
            <div className="bg-white/5 backdrop-blur-3xl rounded-[3rem] p-10 md:p-16 border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.4)] relative overflow-hidden">
                <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-cyan-500 via-blue-500 to-purple-500"></div>
                <div className="relative z-10 flex flex-col items-center text-center">
                    <div className="bg-cyan-500/20 p-6 rounded-full mb-8 ring-4 ring-cyan-500/10">
                        <span className="text-5xl">🎙️</span>
                    </div>
                    <h2 className="text-4xl md:text-5xl font-black text-white mb-6 uppercase tracking-tight">{l.podTitle}</h2>
                    <p className="text-xl text-gray-400 max-w-2xl mb-12 font-medium">
                        {l.podSub}
                    </p>

                    <div className="w-full max-w-2xl">
                        {/* Audio Item Único */}
                        <div className="bg-slate-900/60 p-8 rounded-[2rem] border border-white/5 hover:border-cyan-400/30 transition-all group shadow-2xl">
                            <h4 className="text-white font-bold text-xl mb-6 flex items-center gap-4">
                                <span className="bg-cyan-500 w-10 h-10 rounded-full flex items-center justify-center text-sm shadow-lg shadow-cyan-500/30 group-hover:scale-110 transition-transform text-white">1</span>
                                {l.podFile1}
                            </h4>
                            <audio 
                                controls 
                                className="w-full h-14 filter invert opacity-90 hover:opacity-100 transition-opacity"
                                src={language === 'he' ? "/audio/podcast-he.m4a" : "/audio/podcast-es.m4a"}
                            >
                                Your browser does not support the audio element.
                            </audio>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        );
      default:
        return null;
    }
  };

  return (
    <div className={`min-h-screen flex flex-col bg-[#0b0f1a] ${isRtl ? 'font-hebrew dir-rtl' : 'font-sans dir-ltr'}`}>
      <Header />

      <main className="flex-grow pt-32 pb-24">
        
        {/* HERO TITLE */}
        <section className="px-6 sm:px-8 lg:px-12 text-center mb-20">
          <div className="max-w-5xl mx-auto">
            <h1 className="text-5xl md:text-7xl font-black text-white tracking-tight mb-8 drop-shadow-sm">
                {l.heroTitle}
            </h1>
            <p className="text-xl md:text-3xl text-cyan-400/80 max-w-4xl mx-auto font-medium leading-relaxed">
              {l.heroSub}
            </p>
          </div>
        </section>

        {/* CONTENEDOR TABS Y CONTENIDO */}
        <section className="px-4 sm:px-6 lg:px-8">
          <div className="max-w-7xl mx-auto">
            
            {/* TABS HEADER - STICKY-ish */}
            <div className={`flex flex-wrap items-center justify-center gap-4 mb-12 ${isRtl ? 'flex-row-reverse' : ''}`}>
              {categories.map((cat, idx) => (
                <button
                  key={cat.id}
                  onClick={() => setActiveTab(idx)}
                  className={`px-8 py-4 rounded-2xl font-black text-sm md:text-base uppercase tracking-widest transition-all duration-500 border-2
                    ${activeTab === idx 
                      ? 'text-white bg-cyan-600 border-cyan-400 shadow-[0_0_30px_rgba(6,182,212,0.4)] scale-105' 
                      : 'text-gray-500 bg-white/5 border-transparent hover:border-white/10 hover:bg-white/10'
                    }`}
                >
                  {cat.title}
                </button>
              ))}
            </div>

            {/* TAB CONTENT PANEL */}
            <div className="min-h-[500px]">
              {renderTabContent()}

              {/* CONVERSION BANNER */}
              <div className={`mt-24 bg-gradient-to-br from-[#1e293b] to-[#0f172a] rounded-[3rem] p-10 md:p-16 border border-white/10 shadow-2xl flex flex-col lg:flex-row items-center justify-between gap-10 relative overflow-hidden ${isRtl ? 'flex-row-reverse text-right' : 'text-left'}`}>
                <div className="absolute top-0 right-0 w-96 h-96 bg-cyan-500/10 rounded-full blur-[120px] -mr-48 -mt-48"></div>
                <div className="flex-1 relative z-10">
                  <h4 className="text-4xl md:text-5xl font-black text-white mb-6 leading-tight">
                    <span className="text-cyan-400">⚡</span> {l.bannerTitle}
                  </h4>
                  <p className="text-gray-400 text-xl font-medium max-w-2xl leading-relaxed">
                    {l.bannerSub}
                  </p>
                </div>
                <div className="relative z-10">
                  <Link to="/precios" className="inline-flex py-6 px-12 bg-white text-[#0f172a] hover:bg-cyan-400 hover:text-white rounded-[2rem] font-black transition-all duration-300 shadow-2xl hover:shadow-cyan-500/50 text-xl whitespace-nowrap active:scale-95 leading-none">
                    🚀 {l.bannerBtn}
                  </Link>
                </div>
              </div>
            </div>

          </div>
        </section>

      </main>

      <Footer />
    </div>
  );
};

export default RecursosTabs;
